# Generated by Django 5.0.2 on 2024-03-15 22:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingCycle',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('is_current', models.BooleanField(default=True)),
                ('company_balance', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField()),
                ('role', models.CharField(max_length=255)),
                ('balance', models.IntegerField(default=0)),
                ('is_company', models.BooleanField(default=False, editable=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('title', models.CharField(editable=False, max_length=255)),
                ('is_open', models.BooleanField(default=True)),
                ('closed_at', models.DateTimeField(default=None, null=True)),
                ('assign_price', models.IntegerField(editable=False)),
                ('close_price', models.IntegerField(editable=False)),
                ('assigned_profile', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_created=True, auto_now_add=True, db_index=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('description', models.CharField(editable=False, max_length=255)),
                ('credit', models.IntegerField(default=0, editable=False)),
                ('debit', models.IntegerField(default=0, editable=False)),
                ('billing_cycle', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='accounting.billingcycle')),
                ('profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='accounting.profile')),
            ],
        ),
    ]
